#!/data/data/com.termux/files/usr/bin/bash
echo "[1]Audio only, opus, best quality"
echo "[0]Video (default)"
echo "[5]Update only"
read -n 1 var
case $var in
	1)
		cd $HOME/storage/music
		youtube-dl -x --audio-format opus $1
		;;
	0)
		cd $HOME/storage/movies
		youtube-dl $1
		;;
	5)
		pkg udate && pgk upgrade
		pip install -U youtube-dl
		;;
	*)
		exit 1
esac
