#!/data/data/com.termux/files/usr/bin/bash
echo "[1]Audio only, opus, best quality"
echo "[0]Video (default)"
echo "[5]Update only"
read -n 1 var
case $var in
	1)
		youtube-dl -x --audio-quality 0 --audio-format opus -o "$HOME/storage/music/%(title)s-%(id)s.%(ext)s" $1
		;;
	0)
		youtube-dl -o "$HOME/storage/movies/%(title)s-%(id)s.%(ext)s" $1
		;;
	5)
		pkg update && pkg upgrade
		pip install -U youtube-dl
		;;
	*)
		exit 1
esac
